translations = {
    "en": {
        "title": "AGRONETRA", "subtitle": "AI-Powered Crop Disease Intelligence Platform", "detect_diagnose": "Detect • Diagnose • Protect",
        "nav_home": "Home Workspace", "nav_history": "Analytics History", "nav_analytics": "Live Charts Dashboard",
        "upload_title": "Run Diagnostic Tissue Scan", "upload_desc": "Upload a file or capture a live macro snapshot of the targeted plant foliage.",
        "btn_upload": "Upload Leaf Image", "btn_camera": "Capture Live Leaf", "profile_scope": "User Profile Scope:", "lang_opts": "Global Language Options:",
        "city": "Regional Evaluation City:", "scale": "Scale Quantifier Unit Count:", "btn_predict": "Ingest Frame & Execute Inference",
        "feat_scan": "Disease Scan", "feat_scan_desc": "Deep Convolutional Neural Networks classify anomalies across 29 botanical families instantly.",
        "feat_treat": "Smart Treatment", "feat_treat_desc": "Advisory arrays return dual chemical prescriptions alongside organic mitigation options.",
        "feat_weather": "Weather Intelligence", "feat_weather_desc": "Live meteorological feeds track dewpoint variables and relative localized risk vectors.",
        "feat_reports": "PDF Reports", "feat_reports_desc": "Downloadable enterprise-grade audit reports mapping treatment and financial recovery protocols.",
        "stat_path": "Pathologies Supported", "stat_acc": "Baseline Accuracy", "stat_img": "Images Trained", "stat_active": "AI Analysis Active",
        "compare_btn": "Cross-Compare Disease Baseline Records", "compare_title": "AGRONETRA Cross-Pathology Metrics Matrix",
        "target_genus": "Target Botanical Genus", "status": "Disease Identification", "confidence": "Model Classifier Confidence",
        "severity": "Computer Vision Severity", "gauge_title": "Pathological Diagnostic Severity Gauge", "gauge_desc": "Current Active Evaluation Area:",
        "xai_title": "Explainable AI (XAI) Attribution Localization", "xai_desc": "Visual verification mapping model structural focus coordinates to authenticate pixel deduction arrays",
        "original_img": "Original Leaf Source Ingestion", "heatmap_img": "AI Computer Vision Feature Heatmap", "rationale": "Model Diagnostic Verification Rationale:",
        "simulator_title": "Automated Countermeasure Lifecycle Recovery Simulator", "simulator_desc": "Predictive progression modeling assuming immediate deployment of prescribed remediation parameters",
        "baseline": "Current Ingestion Baseline", "dose_48h": "After Primary Dose (48h)", "stabilization": "Canopy Stabilization (7 Days)",
        "recommendation_title": "Production Recommendation Vector", "read_aloud": "Read Aloud", "profile_assessment": "Pathological Profile Assessment",
        "description": "Description", "symptoms": "Diagnostic Symptoms Identified:", "cause": "Biological Pathogen Cause Agent:",
        "remediation": "Prescriptive Remediation Parameters", "treatment": "Treatment Formulation", "organic": "Organic Treatment Protocol",
        "chemical": "Chemical Countermeasure", "prevention": "Prevention Protocols", "action_plan": "Pipeline Operations", "calendar": "Strategic Field Implementation Calendar",
        "weather_title": "Hyperlocal Microclimate Analysis", "temp": "Temperature Window:", "humidity": "Relative Humidity Rate:", "sky": "Sky Atmosphere:",
        "hazard_risk": "Disease Pathological Propagation Hazard Risk:", "recovery_proj": "Crop Recovery Projection", "outlook": "Outlook Capacity:",
        "priority": "Operational Priority Urgency", "status_tier": "Status Index Tier:", "deadline": "Recommended Deadline:",
        "yield_loss_title": "Yield Deterioration & Economic Loss Matrix", "yield_loss": "Projected Crop Yield Loss", "mitigation_cost": "Mitigation Cost Allocation",
        "net_impact": "Net Financial Field Impact Value Projection:", "ai_doctor": "Conversational AI Copilot Assistant", "btn_spread": "Will it spread?",
        "btn_save": "Can I save my crop?", "btn_cost": "Treatment cost?", "btn_prevent": "Prevention tips?", "placeholder": "Query details about vector spreads, diagnostic steps...",
        "btn_query": "Query Copilot", "btn_download": "Download PDF Audit Report", "btn_new_scan": "Analyze New Crop Target", "footer": "AGRONETRA Crop Intelligence Systems v1.0 © 2026"
    },
    "te": {
        "title": "అగ్రోనేత్ర", "subtitle": "AI-ఆధారిత పంట వ్యాధి ఇంటెలిజెన్స్ ప్లాట్‌ఫారమ్", "detect_diagnose": "గుర్తించండి • నిర్ధారించండి • రక్షించండి",
        "nav_home": "హోమ్ వర్క్‌స్పేస్", "nav_history": "చరిత్ర", "nav_analytics": "లైవ్ చార్ట్‌లు",
        "upload_title": "డయాగ్నస్టిక్ స్కాన్ చేయండి", "upload_desc": "లక్ష్యంగా ఉన్న మొక్క ఆకుల ఫైల్‌ను అప్‌లోడ్ చేయండి లేదా లైవ్ ఫోటో తీయండి.",
        "btn_upload": "ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి", "btn_camera": "లైవ్ కెమెరా తీయండి", "profile_scope": "వినియోగదారు ప్రొఫైల్:", "lang_opts": "భాషా ఎంపికలు:",
        "city": "ప్రాంతీయ మూల్యాంకన నగరం:", "scale": "మొక్కల సంఖ్య:", "btn_predict": "వ్యాధిని నిర్ధారించండి",
        "feat_scan": "వ్యాధి స్కాన్", "feat_scan_desc": "డీప్ న్యూరల్ నెట్‌వర్క్‌లు 29 రకాల వ్యాధులను గుర్తిస్తాయి.",
        "feat_treat": "స్మార్ట్ ట్రీట్మెంట్", "feat_treat_desc": "సేంద్రీయ మరియు రసాయన మందుల సూచనలు.",
        "feat_weather": "వాతావరణ రిస్క్", "feat_weather_desc": "ప్రత్యక్ష వాతావరణ అప్‌డేట్స్.",
        "feat_reports": "PDF రిపోర్ట్‌లు", "feat_reports_desc": "ఆడిట్ నివేదికలను డౌన్‌లోడ్ చేసుకోండి.",
        "stat_path": "వ్యాధుల మద్దతు", "stat_acc": "ఖచ్చితత్వం", "stat_img": "చిత్రాల శిక్షణ", "stat_active": "AI విశ్లేషణ యాక్టివ్",
        "compare_btn": "వ్యాధుల రికార్డులను సరిపోల్చండి", "compare_title": "అగ్రోనేత్ర క్రాస్-పాథాలజీ మాట్రిక్స్",
        "target_genus": "లక్ష్య వృక్షశాస్త్ర జాతి", "status": "వ్యాధి గుర్తింపు", "confidence": "మోడల్ ఖచ్చితత్వం", "severity": "కంప్యూటర్ విజన్ తీవ్రత",
        "gauge_title": "వ్యాధి తీవ్రత గేజ్", "gauge_desc": "ప్రస్తుత మూల్యాంకన ప్రాంతం:", "xai_title": "ఎక్స్‌ప్లెయినబుల్ AI (XAI) హీట్‌మ్యాప్", "xai_desc": "పిక్సెల్ తగ్గింపు శ్రేణులను ప్రామాణీకరించడానికి మ్యాపింగ్.",
        "original_img": "అసలు ఆకు చిత్రం", "heatmap_img": "AI కంప్యూటర్ విజన్ హీట్‌మ్యాప్", "rationale": "మోడల్ నిర్ధారణ హేతువు:",
        "simulator_title": "రికవరీ సిమ్యులేటర్", "simulator_desc": "చికిత్స ప్రణాళికను అమలు చేస్తే రికవరీ పురోగతి.",
        "baseline": "ప్రస్తుత స్థితి", "dose_48h": "మొదటి డోస్ తర్వాత (48 గంటలు)", "stabilization": "స్థిరీకరణ (7 రోజులు)",
        "recommendation_title": "ఉత్పత్తి సిఫార్సు", "read_aloud": "చదివి వినిపించు", "profile_assessment": "వ్యాధి ప్రొఫైల్ అంచనా",
        "description": "వివరణ", "symptoms": "గుర్తించిన లక్షణాలు:", "cause": "వ్యాధి కారకం:", "remediation": "నివారణ చర్యలు", "treatment": "చికిత్స",
        "organic": "సేంద్రీయ చికిత్స", "chemical": "రసాయన చికిత్స", "prevention": "నివారణ ప్రోటోకాల్స్", "action_plan": "చర్య ప్రణాళిక", "calendar": "ఫీల్డ్ అమలు క్యాలెండర్",
        "weather_title": "మైక్రోక్లైమేట్ విశ్లేషణ", "temp": "ఉష్ణోగ్రత:", "humidity": "తేమ:", "sky": "వాతావరణం:", "hazard_risk": "వ్యాధి వ్యాప్తి ప్రమాదం:",
        "recovery_proj": "పంట రికవరీ అంచనా", "outlook": "రికవరీ అవకాశం:", "priority": "ప్రాధాన్యత అత్యవసరం", "status_tier": "స్థితి:", "deadline": "గడువు:",
        "yield_loss_title": "దిగుబడి నష్టం & ఆర్థిక నష్టం", "yield_loss": "అంచనా వేసిన దిగుబడి నష్టం", "mitigation_cost": "చికిత్స ఖర్చు", "net_impact": "నికర ఆర్థిక నష్టం:",
        "ai_doctor": "సంభాషణ AI అసిస్టెంట్", "btn_spread": "ఇది వ్యాపిస్తుందా?", "btn_save": "పంటను రక్షించగలనా?", "btn_cost": "చికిత్స ఖర్చు?", "btn_prevent": "నివారణ చిట్కాలు?",
        "placeholder": "వ్యాప్తి, రోగ నిర్ధారణ లేదా నివారణ గురించి అడగండి...", "btn_query": "ప్రశ్నించండి", "btn_download": "PDF రిపోర్ట్ డౌన్‌లోడ్", "btn_new_scan": "కొత్త ఆకును స్కాన్ చేయండి", "footer": "అగ్రోనేత్ర క్రాప్ ఇంటెలిజెన్స్ సిస్టమ్స్ v1.0 © 2026"
    },
    "hi": {
        "title": "एग्रोनेत्रा", "subtitle": "AI-संचालित फसल रोग इंटेलिजेंस प्लेटफ़ॉर्म", "detect_diagnose": "पता लगाएं • निदान करें • रक्षा करें",
        "nav_home": "होम वर्कस्पेस", "nav_history": "एनालिटिक्स इतिहास", "nav_analytics": "लाइव चार्ट",
        "upload_title": "डायग्नोस्टिक स्कैन चलाएं", "upload_desc": "लक्षित पौधे के पत्ते की फ़ाइल अपलोड करें या लाइव फ़ोटो लें।",
        "btn_upload": "पत्ती की छवि अपलोड करें", "btn_camera": "लाइव कैमरा से खींचें", "profile_scope": "उपयोगकर्ता प्रोफ़ाइल:", "lang_opts": "वैश्विक भाषा विकल्प:",
        "city": "क्षेत्रीय मूल्यांकन शहर:", "scale": "पौधों की संख्या:", "btn_predict": "रोग की भविष्यवाणी करें",
        "feat_scan": "रोग स्कैन", "feat_scan_desc": "डीप न्यूरल नेटवर्क तुरंत 29 वनस्पति परिवारों में विसंगतियों को वर्गीकृत करते हैं।",
        "feat_treat": "स्मार्ट उपचार", "feat_treat_desc": "जैविक शमन विकल्पों के साथ-साथ रासायनिक नुस्खे।",
        "feat_weather": "मौसम इंटेलिजेंस", "feat_weather_desc": "लाइव मौसम संबंधी फ़ीड।",
        "feat_reports": "पीडीएफ रिपोर्ट", "feat_reports_desc": "डाउनलोड करने योग्य उद्यम-ग्रेड ऑडिट रिपोर्ट।",
        "stat_path": "समर्थित रोग", "stat_acc": "सटीकता", "stat_img": "प्रशिक्षित चित्र", "stat_active": "AI विश्लेषण सक्रिय",
        "compare_btn": "रोग रिकॉर्ड की तुलना करें", "compare_title": "एग्रोनेत्रा क्रॉस-पैथोलॉजी मैट्रिक्स",
        "target_genus": "लक्षित वनस्पति जीनस", "status": "रोग की पहचान", "confidence": "मॉडल आत्मविश्वास", "severity": "कंप्यूटर विजन गंभीरता",
        "gauge_title": "रोग गंभीरता गेज", "gauge_desc": "वर्तमान सक्रिय मूल्यांकन क्षेत्र:", "xai_title": "व्याख्यात्मक AI (XAI) हीटमैप", "xai_desc": "दृश्य सत्यापन मैपिंग।",
        "original_img": "मूल पत्ती की छवि", "heatmap_img": "AI कंप्यूटर विजन हीटमैप", "rationale": "मॉडल नैदानिक सत्यापन तर्क:",
        "simulator_title": "रिकवरी सिम्युलेटर", "simulator_desc": "उपचार योजना लागू करने पर रिकवरी की प्रगति।",
        "baseline": "वर्तमान स्थिति", "dose_48h": "प्राथमिक खुराक के बाद (48 घंटे)", "stabilization": "स्थिरीकरण (7 दिन)",
        "recommendation_title": "उत्पादन अनुशंसा", "read_aloud": "जोर से पढ़ें", "profile_assessment": "रोग प्रोफ़ाइल मूल्यांकन",
        "description": "विवरण", "symptoms": "पहचाने गए लक्षण:", "cause": "जैविक रोगजनक कारण:", "remediation": "उपचारात्मक पैरामीटर", "treatment": "उपचार निर्माण",
        "organic": "जैविक उपचार", "chemical": "रासायनिक उपचार", "prevention": "रोकथाम प्रोटोकॉल", "action_plan": "पाइपलाइन संचालन", "calendar": "रणनीतिक क्षेत्र कार्यान्वयन कैलेंडर",
        "weather_title": "हाइपरलोकल माइक्रॉक्लाइमेट विश्लेषण", "temp": "तापमान खिड़की:", "humidity": "सापेक्ष आर्द्रता:", "sky": "आकाश का वातावरण:", "hazard_risk": "रोग प्रसार खतरा जोखिम:",
        "recovery_proj": "फसल रिकवरी अनुमान", "outlook": "आउटलुक क्षमता:", "priority": "परिचालन प्राथमिकता", "status_tier": "स्थिति सूचकांक:", "deadline": "अनुशंसित समय सीमा:",
        "yield_loss_title": "उपज में गिरावट और आर्थिक नुकसान", "yield_loss": "अनुमानित फसल उपज हानि", "mitigation_cost": "शमन लागत आवंटन", "net_impact": "शुद्ध वित्तीय प्रभाव:",
        "ai_doctor": "संवादात्मक एआई कोपायलट", "btn_spread": "क्या यह फैलेगा?", "btn_save": "क्या मैं अपनी फसल बचा सकता हूँ?", "btn_cost": "उपचार की लागत?", "btn_prevent": "रोकथाम के उपाय?",
        "placeholder": "वेक्टर प्रसार, नैदानिक कदम के बारे में पूछें...", "btn_query": "क्वेरी कोपायलट", "btn_download": "पीडीएफ ऑडिट रिपोर्ट डाउनलोड करें", "btn_new_scan": "नए लक्ष्य का विश्लेषण करें", "footer": "एग्रोनेत्रा क्रॉप इंटेलिजेंस सिस्टम्स v1.0 © 2026"
    }
}